### PR TITLE
remove skidware

### PR DESCRIPTION
**Pull request by jvyden**

### CODE REVIEW

**Comment by rosenishere** [comment]
dude shut up please I never asked for any opinion or something stop messing with me like go play your oldsu and leave me alone

**Comment by jvyden** [comment]
skid btfo

**Comment by rosenishere** [comment]
dude what do you want from me

**Comment by jvyden** [comment]
rosen is here more like rosen got btfo'd ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Pull request closed without merging**
